export const GreekEcoursesData = {
  // method that returns an array of Ecourse objects that appear in Home page
  getGreekHomePageEcourseData() {
    return [
      {
        id: "1000",
        title: "Web Develoaaapment Bootcamp",
        image: img,
        price: 650,
        category: "Προγραμματισμός",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1001",
        title: "Άλγεβρα 2",
        image: img,
        price: 650,
        category: "Μαθηματικά",
        ecourseLocation: "Εξ Αποστάσεως",

        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1002",
        title: "Τεχνητή Νοημοσύνη",
        image: img,
        price: 650,
        category: "Φυσική",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1003",
        title: "Άλγεβρα 1",
        image: img,
        price: 650,
        category: "Βιολογία",
        ecourseLocation: "Δια Ζώσης",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1004",
        title: "Python Bootcamp",
        image: img,
        price: 650,
        category: "Αγγλική Φιλολογία",
        ecourseLocation: "Δια Ζώσης",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1005",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ελληνική Φιλολογία",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1006",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Γλωσσολογία",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1007",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ψυχολογία",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1008",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ιστορία",
        ecourseLocation: "Δια Ζώσης",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
    ];
  },

  // method that returns an array of All Ecourse objects
  getGreekAllEcoursesData() {
    return [
      {
        id: "1000",
        title: "Web Develoaaapment Bootcamp",
        image: img,
        price: 650,
        category: "Προγραμματισμός",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1001",
        title: "Άλγεβρα 2",
        image: img,
        price: 650,
        category: "Μαθηματικά",
        ecourseLocation: "Εξ Αποστάσεως",

        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1002",
        title: "Τεχνητή Νοημοσύνη",
        image: img,
        price: 650,
        category: "Φυσική",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1003",
        title: "Άλγεβρα 1",
        image: img,
        price: 650,
        category: "Βιολογία",
        ecourseLocation: "Δια Ζώσης",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1004",
        title: "Python Bootcamp",
        image: img,
        price: 650,
        category: "Αγγλική Φιλολογία",
        ecourseLocation: "Δια Ζώσης",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1005",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ελληνική Φιλολογία",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1006",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Linguistics",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1007",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ψυχολογία",
        ecourseLocation: "Yβριδική",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1008",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "History",
        ecourseLocation: "Δια Ζώσης",
        university: "Πανεπιστήμιο Πειραιώς",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1009",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Φιλοσοφία",
        ecourseLocation: "Yβριδική",
        university: "Εθνικό Μετσόβιο Πολυτεχνείο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 4,
      },
      {
        id: "1010",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Μηχανική",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Εθνικό Μετσόβιο Πολυτεχνείο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 3,
      },
      {
        id: "1011",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Τέχνη",
        ecourseLocation: "Δια Ζώσης",
        university: "Εθνικό Μετσόβιο Πολυτεχνείο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 2,
      },
      {
        id: "1012",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Προγραμματισμός",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Οικονομικό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 4,
      },
      {
        id: "1013",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Μαθηματικά",
        ecourseLocation: "Yβριδική",
        university: "Οικονομικό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 11,
      },
      {
        id: "1014",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Φυσική",
        ecourseLocation: "Yβριδική",
        university: "Οικονομικό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1015",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Βιολογία",
        ecourseLocation: "Δια Ζώσης",
        university: "Οικονομικό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 4,
      },
      {
        id: "1016",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Αγγλική Φιλολογία",
        ecourseLocation: "Yβριδική",
        university: "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 4.5,
      },
      {
        id: "1017",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ελληνική Φιλολογία",
        ecourseLocation: "Δια Ζώσης",
        university: "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1018",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Linguistics",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1019",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Law",
        ecourseLocation: "Yβριδική",
        university: "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1020",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Ψυχολογία",
        ecourseLocation: "Yβριδική",
        university: "Πάντειον Πανεπιστήμιο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1021",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Αρχαιολογία",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Πάντειον Πανεπιστήμιο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1022",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Φιλοσοφία",
        ecourseLocation: "Δια Ζώσης",
        university: "Πάντειον Πανεπιστήμιο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1023",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Μηχανική",
        ecourseLocation: "Yβριδική",
        university: "Πάντειον Πανεπιστήμιο",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1024",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Art",
        ecourseLocation: "Δια Ζώσης",
        university: "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1025",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Προγραμματισμός",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1026",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Προγραμματισμός",
        ecourseLocation: "Δια Ζώσης",
        university: "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
      {
        id: "1027",
        title: "Web Development Bootcamp",
        image: img,
        price: 650,
        category: "Προγραμματισμός",
        ecourseLocation: "Εξ Αποστάσεως",
        university: "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης",
        professors: ["Δημήτρης Δημήτρης", "Γαβαλάς Γαβαλάς"],
        duration: "12 εβδομάδες",
        ECTS: 6,
        language: ["Ελληνικά", "Αγγλικά"],
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        rating: 5,
      },
    ];
  },

  // method that returns an array of different universities.
  getUniversityNameGreek() {
    return [
      {
        id: "2000",
        name: "Πανεπιστήμιο Πειραιώς",
      },
      {
        id: "2001",
        name: "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών",
      },
      {
        id: "2002",
        name: "Εθνικό Μετσόβιο Πολυτεχνείο",
      },
      {
        id: "2003",
        name: "Πανεπιστήμιο Δυτικής Αττικής",
      },
      {
        id: "2004",
        name: "Οικονομικό Πανεπιστήμιο Αθηνών",
      },
      {
        id: "2005",
        name: "Πάντειον Πανεπιστήμιο",
      },
      {
        id: "2006",
        name: "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης",
      },
    ];
  },

  //  method that returns a Promise that resolves with all ecourses from getHomePageEcourseData.
  getEcoursesHomePage() {
    return Promise.resolve(this.getGreekHomePageEcourseData());
  },

  //  method that returns a Promise that resolves with all Ecourses from getAllEcourses.
  getAllEcourses() {
    return Promise.resolve(this.getGreekAllEcoursesData());
  },
};
